create
user kitty superuser; -- создать пользователя для проекта
alter
user kitty password 'purrr'; -- задать пароль пользователя
create
database cats with owner kitty; -- создать базу данных проекта и её владельца

-- предыдущие шаги вы выполнили в визуальном клиенте. Попробуйте выполнить дальнейшие шаги в консольном клиенте после нажатия на кнопку >_

create table cat_user
(
    id       varchar(64) not null, -- идентификатор текстовый, соответствует логину
    username varchar(255) default 'noname cat',
    nickname varchar(255)
); -- создайте таблицу пользователей Catsgram

create unique index user_id_uindex
    on cat_user (id);
-- индекс, чтобы базе данных было легче искать пользователей



create table cat_post
(
    id            int generated by default as identity primary key, -- идентификатор целочисленный, автоинкрементный
    author_id     varchar(64) not null,
    description   varchar(500),
    photo_url     varchar(1000),
    creation_date timestamp,
    CONSTRAINT fk_post_author
        FOREIGN KEY (author_id)
            REFERENCES cat_user (id)
); -- затем создайте таблицу с постами пользователей — это то место, где будут храниться все котики



create table cat_follow
(
    id          int generated by default as identity primary key,
    author_id   varchar(64) REFERENCES cat_user(id),
    follower_id varchar(64) REFERENCES cat_user(id)
);



create table cat_chat
(
    id        int generated by default as identity primary key,
    user_from varchar(64), --REFERENCES cat_user(id),
    user_to   varchar(64), --REFERENCES cat_user(id),
    send_date timestamp,
    message   varchar(1024),
    user_read boolean
    CONSTRAINT fk_user_from
            FOREIGN KEY (user_from)
                REFERENCES cat_user (id)
    CONSTRAINT fk_user_to
                FOREIGN KEY (user_to)
                    REFERENCES cat_user (id)
);


